environment: dev

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: dev.k8s-13.sa
      paths:
        - path: /
          pathType: Prefix

wordpress:
  url: http://dev.k8s-13.sa
  title: Dev
