environment: prod

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: project.k8s-13.sa
      paths:
        - path: /
          pathType: Prefix

wordpress:
  url: http://project.k8s-13.sa
  title: Project
