apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wordpress.fullname" . }}-post-install
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
  labels:
    app.kubernetes.io/name: {{ include "wordpress.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: wp-storage
          persistentVolumeClaim:
            claimName: {{ include "wordpress.fullname" . }}-pvc
      containers:
      - name: wp-install
        image: wordpress:cli
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: host
        - name: HTTP_HOST
          value: {{ .Values.wordpress.url | quote }}
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: db-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: db-password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: db-name
        - name: WORDPRESS_URL
          value: {{ .Values.wordpress.url | quote }}
        - name: WORDPRESS_TITLE
          value: {{ .Values.wordpress.title | quote }}
        - name: WORDPRESS_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: admin-user
        - name: WORDPRESS_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: admin-pswd
        - name: WORDPRESS_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: admin-email
        - name: WORDPRESS_THEME
          value: {{ .Values.wordpress.theme | quote }}
        volumeMounts:
          - name: wp-storage
            mountPath: /var/www/html
        command: ["/bin/sh", "-c"]
        args:
          - |
          #  until wp core is-installed --path=/var/www/html; do
          #    echo "Waiting for WordPress to be ready..."
          #    sleep 10
          #  done

            if ! wp core is-installed --path=/var/www/html; then
              wp core install \
                --path=/var/www/html \
                --url="$WORDPRESS_URL" \
                --title="$WORDPRESS_TITLE" \
                --admin_user="$WORDPRESS_ADMIN_USER" \
                --admin_password="$WORDPRESS_ADMIN_PASSWORD" \
                --admin_email="$WORDPRESS_ADMIN_EMAIL" \
                --skip-plugins
            fi

            echo "Change theme"
            wp theme install $WORDPRESS_THEME --path=/var/www/html --activate

            ACTIVE_THEME=$(wp theme list --path=/var/www/html --status=active --field=name)
            if [ "$ACTIVE_THEME" != "$WORDPRESS_THEME" ]; then
              echo "Failed to activate theme: $WORDPRESS_THEME"
              exit 1
            fi

            echo "Theme $WORDPRESS_THEME activated successfully!"
